apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secrets
  namespace: acquisitions
  labels:
    app: acquisitions
type: Opaque
# Values are base64 encoded
# To encode: echo -n 'your-value' | base64
# To decode: echo 'encoded-value' | base64 -d
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfdlJmbXFBZFE5VjhpQGVwLWxpbmdlcmluZy1hcnQtYWdnNWh1aHotcG9vbGVyLmMtMi5ldS1jZW50cmFsLTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl
  JWT_SECRET: azhzLXNlY3VyZS1qd3Qtc2VjcmV0LXByb2R1Y3Rpb24tODQ5MjcxLWFjcXVpc2l0aW9ucw==
